[package]
name = "klaw-ui-kit"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Shared UI foundation for klaw-gui and klaw-webui"

[features]
default = ["fonts-lxgw"]
fonts-lxgw = []
fonts-noto-sans = []

[dependencies]
egui = { workspace = true }
catppuccin-egui = { workspace = true }
egui-phosphor = { workspace = true }
egui-notify = { workspace = true }
egui-theme-switch = { workspace = true }
egui-twemoji = { workspace = true }
eframe = { workspace = true }
serde = { workspace = true, features = ["derive"] }
rand = { workspace = true }
rust-embed = { workspace = true }
unic-langid = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
fontdb = { workspace = true }
i18n-embed = { workspace = true, features = ["fluent-system", "desktop-requester"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { workspace = true }
i18n-embed = { workspace = true, features = ["fluent-system", "web-sys-requester"] }
