[book]
title = "Klaw Documentation"
authors = ["zhubby"]
language = "zh-CN"
src = "src"
description = "Klaw - Rust-based AI Agent"

[output.html]
git-repository-url = "https://github.com/zhubby/klaw"
git-repository-icon = "fa-github"
additional-js = ["mermaid.min.js", "mermaid-init.js"]
additional-css = ["./theme/catppuccin.css"]
default-theme = "latte"
preferred-dark-theme = "mocha"

[output.html.fold]
enable = true
level = 1

[preprocessor.mermaid]
command = "mdbook-mermaid"
optional = true
